platform :ios, '9.0'

target 'AudioKnjige' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AudioKnjige

pod 'SwiftyJSON'
pod 'AudioPlayerSwift'

end
